[program: vicuna7b_ft_v12_data_server]
command = /home/huangjiahong.dracu/miniconda2/envs/vits/bin/gunicorn -c gunicorn_conf.py qas_data_server:app  --error-logfile /mnt/cephfs/hjh/logs/data_qas/supervisor_err.log
directory = /home/huangjiahong.dracu/hjh/pycharm_projects/nlp/stanford_alpaca/run_shells/train/vicuna-7b-1.1/ft_v12/data_server
user = root ;
autostart=true ;
autorestart=true ;
redirect_stderr=true ;
logfile_backups=10 ;
stdout_logfile_backups=10 ;
logfile_maxbytes=25MB ;
stderr_logfile=/mnt/cephfs/hjh/logs/data_qas/supervisor_err.log ;
stdout_logfile=/mnt/cephfs/hjh/logs/data_qas/supervisor_info.log ;
